summary: XML-based font configuration tools
webpage: https://wiki.freedesktop.org/www/Software/fontconfig
version: 2.15.0
bin-url: https://github.com/leleliu008/uppm-package-repository-android-35-aarch64/releases/download/2025.01.24/fontconfig-2.15.0-android-35-arm64-v8a.release.tar.xz
bin-sha: b37b70391f4d2d4fab8ca98414782e4cd81edd6775677eb0f3acb870faccb510
