summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-android-35-aarch64/releases/download/2025.01.24/pkg-config-0.29.2-android-35-arm64-v8a.release.tar.xz
bin-sha: 54ead8e889d96133d98122eb76c42ebe419d8ce9de0d2304ca717203d9edcd6f
